### ISSUE TITLE
フィードバック(?)とバグ(?)報告

### ISSUE THREAD

**Issue by wisemanjr4** [grc-mcs/pomkots-mechs#3]
**バグ**
ロボが何かしらのモーション中に降機すると空中で固定される。

**バグ(?)**
GUIの大きさを自動以外にするとサイト内に入っているのに誘導できない・逆に入っていないのに誘導できるという状況が生まれる

**フィードバック**
Quilt環境での動作を確認しました。

**Comment by grc-mcs** [comment]
@wisemanjr4 

おおお、いつもありがとうございます！
Forge対応を倒したらチケット分割していきます！

**Comment by grc-mcs** [comment]
二つのチケット #5 #6 に分割したので、このチケットはクローズします！
状況の追跡は分割したチケットの方でおねしゃす！
